script:
- git remote add upstream $GIT_URL
- |
  curl -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/repos/$GITHUB_NAME/$GITHUB_REPO > lol.txt
- git remote add fork $(cat lol.txt | jq -r '.clone_url')
- git fetch upstream $(cat lol.txt | jq -r '.default_branch')
- echo -e "machine github.com\nlogin $GITHUB_NAME\npassword $GITHUB_TOKEN" >> ~/.netrc
- git push fork upstream/$(cat lol.txt | jq -r '.default_branch'):$(cat lol.txt | jq -r '.default_branch')
branches:
  except:
    - /^deploy-.*$/
notifications:
  email: false
env:
  global:
  - GITHUB_NAME=$(echo $TRAVIS_REPO_SLUG | cut -d '/' -f 1)
  matrix:
  - GITHUB_REPO=peerguardian GIT_URL=https://git.code.sf.net/p/peerguardian/code
  - GITHUB_REPO=stg GIT_URL=http://git.stg.codes/stg.git
  - GITHUB_REPO=orbot GIT_URL=https://git.torproject.org/orbot.git
  - GITHUB_REPO=tor GIT_URL=https://git.torproject.org/tor.git
