version: 2
jobs:
  build:
    docker:
      - image: galeksandrp/travistest:docker-build-android-jdk7
    steps:
      - run: echo 'export PATH=~/bin:$PATH' >> $BASH_ENV
      - run: mkdir -p ~/.ssh
      - run: ssh-keyscan -H github.com >> ~/.ssh/known_hosts
      - run: repo init -u $(echo $CIRCLE_REPOSITORY_URL | tr ':' '/' | sed 's&^git@&git://&') -b $CIRCLE_BRANCH
      - run: repo sync -c
      - run: source build/envsetup.sh && sh vendor/cm/get-prebuilts
      - run: export TERM=xterm && source build/envsetup.sh && brunch cooper
      - store_artifacts:
          path: out/target/product/cooper
    working_directory: ~/work
